### ISSUE TITLE
WARNING: `Eval()` was called from an async context. Please use `await EvalAsync()` instead.

### ISSUE THREAD

**Issue by S4mpl3r** [braintrustdata/braintrust-sdk#450]
Hi there, I recently stumbled upon `braintrust` and followed the quickstart guide for the Python SDK. Everything worked out, however, I get this annoying warning in the terminal when I run the `python eval eval_tutorial.py` command:
```
WARNING: `Eval()` was called from an async context. Please use `await EvalAsync()` instead.
Call stack:
<STACK TRACE HERE>
```
Is this a bug?

**Comment by ankrgyl** [comment]
Hi, did you run it in a notebook? The warning is saying that you're running `Eval` somewhere async, and you should use `EvalAsync` instead.

**Comment by S4mpl3r** [comment]
@ankrgyl No, I'm just running a simple script named `eval_tutorial.py` with `braintrust eval eval_tutorial.py`, as per the quickstart guide for python. Here's my code:
```
from autoevals import LevenshteinScorer
from braintrust import Eval

Eval(
    "Say Hi Bot",
    data=lambda: [
        {
            "input": "Foo",
            "expected": "Hi Foo",
        },
        {
            "input": "Bar",
            "expected": "Hello Bar",
        },
    ],  # Replace with your eval dataset
    task=lambda input: "Hi " + input,  # Replace with your LLM call
    scores=[LevenshteinScorer],
)
```

**Comment by ankrgyl** [comment]
Ah ok, let us understand why the warning is being triggered, and will resolve.

In the meantime, you can ignore it -- the `Eval` call will actually work just fine.

**Comment by S4mpl3r** [comment]
@ankrgyl Yeah, sure thing. On a separate note, my first impression of the braintrust platform is very positive. Keep it up!

**Comment by kevin1** [comment]
@S4mpl3r Thank you for the feedback! We are removing this warning in the next release of the `braintrust` CLI.
