### ISSUE TITLE
TYPO : Your main README's title has a typo Brainrust SDK -> Braintrust SDK

### ISSUE THREAD

**Issue by jskwak98** [braintrustdata/braintrust-sdk#73]
![스크린샷 2023-12-21 오후 6 13 43](https://github.com/braintrustdata/braintrust-sdk/assets/47588410/af3371a2-619a-449c-aa00-de84a975ab7c)

I was deeply impressed by what Braintrust is aiming to do! I do agree that we need a nicely integrated interface that can evaluate the performance of AI models, especially LLMs.

Hope you guys keep up the good work and add more amazing features. Thanks!

**Comment by ankrgyl** [comment]
Thank you so much! I just fixed it [here](https://github.com/braintrustdata/braintrust-sdk/commit/24a2b38efaae2f843f6ea2e12931ee08b50b28f0)
